server:
  port: 8081
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/employee_db'
    username: 'postgres'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  boot:
    message: 'Hello! Employee Service configs updated for SpringCloud Bus demo'

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: 'http://localhost:8761/eureka/'
